import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { getPrimaryMenu } from "@/lib/graphql/queries/getPrimaryMenu";
import { getFooter } from "@/lib/graphql/queries/getFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { menu, logo } = await getPrimaryMenu();
  const {footer, logo: footerLogo} = await getFooter();
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header menu={menu} logo={logo} />
        {children}
        <Footer footer={footer} logo={footerLogo} />
      </body>
    </html>
  );
}
